[workspace]
resolver = "2"
members = [
    "faust_jit",
    "faust_jit_egui",
    "nih_faust_jit",
    "nih_faust_jit/xtask",
    "cpal_faust_jit",
]

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
