[alias]
xtask = "run --package xtask --release --"

[env]
# env vars will be set unless they are already present, so these are just
# defaults:
FAUST_LIB = "static=libfaustwithllvm"
FAUST_LIB_PATH = "C:/Program Files/Faust/lib"
FAUST_HEADERS_PATH = "C:/Program Files/Faust/include"
DSP_LIBS_PATH = "C:/Program Files/Faust/share/faust"
